name: Deploy to Server

on:
  push:
    branches:
      - main  # O 'master', dependiendo de tu proyecto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 5118
        script: |
          cd /Saas_Virgen_de_Lourdes/
          git pull origin main  # O 'master', dependiendo de la rama
          cp -f build/* /var/www/minimarket-frontend
          sudo systemctl reload nginx
          
