name: Deploy Frontend to Server

on:
  push:
    branches:
      - main  # O 'master', dependiendo de tu proyecto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Instalar dependencias para ejecutar las pruebas
    - name: Install dependencies
      run: |
        npm install  # Cambia este comando si usas yarn u otro gestor

    # Ejecutar las pruebas
  

    - name: Set up known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || true

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to server via SSH
      run: |
        ssh -i ~/.ssh/front_id_rsa -o StrictHostKeyChecking=no -p 5118 root@149.50.132.9 << 'EOF'
          set -e

          # Navegar al directorio del proyecto frontend
          cd /Saas_Virgen_de_Lourdes/

          # Hacer pull de los últimos cambios en la rama 'main'
          git pull origin main

          # Copiar los archivos del build al servidor web
          cp -f build/* /var/www/minimarket-frontend

          # Recargar nginx
          sudo systemctl reload nginx
        EOF
